[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.7" }
jqwik = { module = "net.jqwik:jqwik", version = "1.9.3" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.3" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.21.0" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version = "0.53.0"}
test-logger = { id = "com.adarshr.test-logger", version = "4.0.0" }
use-latest-versions = { id = "se.patrikerdes.use-latest-versions", version = "0.2.19" }
